"""borrower

Revision ID: d46874c42d10
Revises: f27974ce98d0
Create Date: 2023-03-17 12:44:35.782868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46874c42d10'
down_revision = 'f27974ce98d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_author_name'), ['author_name'], unique=False)

    with op.batch_alter_table('homelibrary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_homelibrary_author')
        batch_op.create_index(batch_op.f('ix_homelibrary_author'), ['author'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homelibrary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homelibrary_author'))
        batch_op.create_index('ix_homelibrary_author', ['author'], unique=False)
        batch_op.drop_column('borrowed')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_author_name'))

    op.drop_table('author')
    # ### end Alembic commands ###
