"""homelibrary

Revision ID: f27974ce98d0
Revises: 
Create Date: 2023-03-17 12:38:20.416181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27974ce98d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homelibrary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homelibrary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homelibrary_author'), ['author'], unique=True)
        batch_op.create_index(batch_op.f('ix_homelibrary_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homelibrary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homelibrary_title'))
        batch_op.drop_index(batch_op.f('ix_homelibrary_author'))

    op.drop_table('homelibrary')
    # ### end Alembic commands ###
